name: Distribution Packages
on:
  push:
    branches:
      - main
permissions:
  checks: write
  actions: read
  contents: write
jobs:
  docs-site:
    name: docs.mg105.com Javadoc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Generate Javadoc
        uses: gradle/gradle-build-action@v2
        with:
          arguments: javadoc
      - name: Create .nojekyll File
        run: touch build/docs/javadoc/.nojekyll
      - name: Set Domain Name
        run: echo "docs.mg105.com" > build/docs/javadoc/CNAME
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/docs/javadoc
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Generate Tarball Distribution
        uses: gradle/gradle-build-action@v2
        with:
          arguments: distTar
      - name: Generate Zip Distribution
        uses: gradle/gradle-build-action@v2
        with:
          arguments: distZip
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          name: Prerelease for ${{ github.sha }}
          body: This release is created automatically via GitHub actions. Its artifacts are based on ${{ github.sha }}.
          tag: prerelease
          commit: ${{ github.sha }}
          prerelease: true
          artifacts: 'build/distributions/*'
