name: Sanity Checks
on: [pull_request]
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  untouchable-files:
    name: Untouchable Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Prevent changes to .idea/* files
        uses: xalvarez/prevent-file-change-action@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          pattern: .idea/.*.xml
